-- AlterTable
ALTER TABLE `blogs` ADD COLUMN `blogIndex` VARCHAR(191) NOT NULL DEFAULT '0',
    ADD COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `displayOnHome` VARCHAR(191) NOT NULL DEFAULT 'false';
